### ISSUE TITLE
Switch to markdown renderer

### ISSUE THREAD

**Issue by gregcorbett** [GOCDB/GOCDB.github.io#4]
I'd certainly prefer dealing with markdown rather than HTML, and it should be possible: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll

**Comment by tofu-rocketry** [comment]
APEL does this: https://github.com/apel/apel.github.io
